spring:
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://3.34.79.67/login/oauth2/code/kakao

server:
  port: 8080
  serverAddress: 3.34.79.67

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://3.34.79.67/login/oauth2/code/kakao

server:
  port: 8081
  serverAddress: 3.34.79.67

serverName: green_server