name: Enforce Branch Rules

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  enforce_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR reviews
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const approved = reviews.data.filter(r => r.state === "APPROVED");
            if (approved.length < 1) {
              core.setFailed("이 PR은 최소 1명의 Approve가 필요합니다.");
            }
